name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: "-D warnings"

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  lint-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: cargo clippy

      - name: Format
        run: cargo fmt -- --check
